# Generated by Django 5.2.5 on 2025-09-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'package', 'verbose_name_plural': 'packages'},
        ),
        migrations.AlterModelOptions(
            name='packageattribute',
            options={'verbose_name': 'package attribute', 'verbose_name_plural': 'package attributes'},
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='package',
            name='days',
            field=models.PositiveIntegerField(verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='is_enabled'),
        ),
        migrations.AlterField(
            model_name='package',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_at'),
        ),
        migrations.AlterField(
            model_name='package',
            name='months',
            field=models.PositiveSmallIntegerField(verbose_name='months'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.BigIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='packageattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='packageattribute',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_at'),
        ),
        migrations.AlterField(
            model_name='packageattribute',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='package.package', verbose_name='package'),
        ),
        migrations.AlterField(
            model_name='packageattribute',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
