# Generated by Django 5.2.5 on 2025-09-09 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='gateway title')),
                ('gateway_request_url', models.CharField(blank=True, max_length=120, null=True, verbose_name='request URL')),
                ('gateway_verify_url', models.CharField(blank=True, max_length=120, null=True, verbose_name='verify URL')),
                ('gateway_code', models.CharField(choices=[('saman', 'Saman'), ('shaparak', 'Shaparak'), ('finothech', 'Finothech'), ('zarinpal', 'Zarinpal'), ('parsian', 'Parsian')], max_length=120, verbose_name='gateway code')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
                ('auth_data', models.TextField(blank=True, null=True, verbose_name='auth data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='invoice number')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('payment_log', models.TextField(blank=True, verbose_name='payment log')),
                ('authority', models.CharField(blank=True, max_length=64, verbose_name='authority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.gateway', verbose_name='gateway')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchase.purchase')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
