# Generated by Django 5.2.5 on 2025-09-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_options_alter_packageattribute_options_and_more'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'purchase', 'verbose_name_plural': 'purchases'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='package.package', verbose_name='package'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'Paid'), (-10, 'No Paid')], default=-10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
